### PR TITLE
Serializer key

### PR DESCRIPTION
**Pull request by WilsontheWolf**
So funny story. I wrote this code and made sure it worked. Then I forget to push :facepalm:. Here is the fix.

### CODE REVIEW

**Review by thetayloredman — APPROVED** [review]
# Approval and Meta from @thetayloredman (AKA `BadBoyHaloCat`)

## Approval

Lol big oof

## Meta

**Commit(s) Affect(s)**: `src/index.js:120`

**Diff(s)**:

```
@@ -117,7 +117,7 @@ class Josh {
117      */
118     async get(keyOrPath) {
119       await this.readyCheck();
120  -    const [key, path] = this.getKeyAndPath(keyOrPath);
120  +    const [key, ...path] = this.getKeyAndPath(keyOrPath);
121       const hasKey = await this.has(keyOrPath);
122       let value;
123       if (!hasKey) {
```

**Author(s)**:

* @WilsontheWolf

**Type**: *Pull Request*

### Pull Request Meta

**Branch**: `WilsontheWolf:serializer-key`

**Name**: *Serializer Key*

## Oof Level

100%

## Commit History

<details>

<summary>Commit History</summary>

```
                                                            .───────────.
                                                         ,─'             '─.
                                                      ,─'                   '─.
                                                     ╱                         ╲
                                                   ,'                           `.
                                                  ;                               :
                                                  ;┌──────────────────────────────┐
                                                 ; │           HEAD at:           │:
                                                 │ │ WilsontheWolf:serializer-key ││
                                                 │ │                              ││
                                                 : └──────────────────────────────┘;
                                                  :                               ;
        ┌────────────────────────────┐            :                               ;
        │WilsontheWolf:serializer-key│             ╲                             ╱
        └────────────*───────────────┘              `.                         ,'
                     *                                ╲                       ╱
                     *                                 '─.                 ,─'
                     *                                    '─.           ,─'
                     *                                       `─────────'
                     *   ┌─────────┐                         ┌─────────┐
                     *   │ 491180  │                         │ 0b7f9d6 │
                     *   └─────────┘                         └─────────┘
                     *
                     *      .───.                               .───.
                     *     ;     :                             ;     :
             ┌───────*────▶:     ;────────────────────────────▶:     ;
             │              ╲   ╱                               ╲   ╱
             │               `─'                                 `─'
             │
             │
             │
             │
             │
─────────────*────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────▶
             *
  ┌──────────*──────┐
  │Eschalance:master│
  └─────────────────┘
```

</details>

#### *I am a human providing a service. If you found any problems with this feel free to DM me on Discord: `@BadBoyHaloCat#1826`*

**Comment by thetayloredman** [comment]
Lol ignore that I was testing out some markdown

**Comment by WilsontheWolf** [comment]
ok nvm idk how to commit josh

**Comment by eslachance** [comment]
Josh disapproves of this PR :P

**Comment by thetayloredman** [comment]
# PR Archive because why not

**WilsontheWolf**: *Opened this PR*

**thetayloredman**: *Approved this PR*

**thetayloredman**: *Commented*

**thetayloredman**: *Commented*

**WilsontheWolf**: *Commented*

**WilsontheWolf**: *Closed this PR*

**JOSH**: *disapproves*

**eslachance**: *Comments / Ruins a person's day*

**Comment by thetayloredman** [comment]
> *Comments / Ruins a person's day*

###### evie in a nutshell

**Comment by JOSH-Javascript-Object-Storage-Handler** [comment]
> Josh disapproves of this PR :P 

When did I say that, @eslachance?

**Pull request closed without merging**
