### PR TITLE
Added Josh.multi

### PR DESCRIPTION
**Pull request by WilsontheWolf**
Behaves identically to Enmap.multi.

### CODE REVIEW

**Comment by thetayloredman** [comment]
noice

**Review by thetayloredman — APPROVED** [review]

**Comment by eslachance** [comment]
Sorry, I'd already added josh.multi by the time you wrote this, but I hadn't pushed it yet as I was doing a larger refactor!

**Comment by WilsontheWolf** [comment]
oof

**Comment by thetayloredman** [comment]
# OOF SIZE

## 100%

**Pull request closed without merging**
